apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ttzf2zavj-nodejs 
  janus-idp.io/tekton: ttzf2zavj-nodejs
  backstage.io/kubernetes-id: ttzf2zavj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ttzf2zavj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml